export const initialState = [
  {
    id: 1,
    text: 'Learn Redux',
    completed: false,
    color: '#02a8f3',
  },
  {
    id: 2,
    text: 'Learn React',
    completed: false,
    color: '#02a8f3',
  },
  {
    id: 3,
    text: 'Learn React Router',
    completed: false,
    color: '#02a8f3',
  },
  {
    id: 4,
    text: 'Learn Redux Saga',
    completed: false,
    color: '#02a8f3',
  },
  {
    id: 5,
    text: 'Learn Redux Thunk',
    completed: false,
    color: '#02a8f3',
  },
  {
    id: 6,
    text: 'Learn Redux Form',
    completed: false,
    color: '#02a8f3',
  },
  {
    id: 7,
    text: 'Learn Redux Selectors',
    completed: false,
    color: '#02a8f3',
  },
  {
    id: 8,
    text: 'Learn Redux Hooks',
    completed: false,
    color: '#02a8f3',
  },
  {
    id: 9,
    text: 'Learn Redux Thunk',
    completed: false,
    color: '#02a8f3',
  },
  {
    id: 10,
    text: 'Learn Redux Form',
    completed: false,
    color: '#02a8f3',
  },
  {
    id: 11,
    text: 'Learn Redux Selectors',
    completed: false,
    color: '#02a8f3',
  },
  {
    id: 12,
    text: 'Learn Redux Hooks',
    completed: false,
    color: '#02a8f3',
  },
  {
    id: 13,
    text: 'Learn Redux Thunk',
    completed: false,
    color: '#02a8f3',
  },
  {
    id: 14,
    text: 'Learn Redux Form',
    completed: false,
    color: '#02a8f3',
  },
  {
    id: 15,
    text: 'Learn Redux Selectors',
    completed: false,
    color: '#02a8f3',
  },
  {
    id: 16,
    text: 'Learn Redux Hooks',
    completed: false,
    color: '#02a8f3',
  },
  {
    id: 17,
    text: 'Learn Redux Thunk',
    completed: false,
    color: '#02a8f3',
  },
]
